### ISSUE TITLE
Add prop: onlyMainProcess

### ISSUE THREAD

**Issue by erikaperugachi** [nucleus-sh/nucleus-nodejs#1]
I want to use this module to _main process_. But I have active `nodeIntegration: true` by others modules that these need it.
I see that by default, your module change to _renderer process_ when I have activated nodeIntegration, check that: I don't necessarily I have activated that for your module.

I prefer use the prop: `onlyMainProcess` like before.

**Comment by vincelwt** [comment]
Hi!
I'm not sure I fully understand the problem here. The new version of this module should automatically pick up the available features depending on if it's added to the main process, renderer process and whether it has access to Node modules. 
So it should work in both processes with or without the `nodeIntegration` enabled. Isn't that the case?
