### ISSUE TITLE
localStorage is not defined

### ISSUE THREAD

**Issue by fonts-ninja** [nucleus-sh/nucleus-nodejs#3]
On MacOS when packaging for Electron and launching the app normaly it will result in this error.

When launching the app executable (AppName.app/Contents/MacOS/AppName) works for some reason (writable cwd?).

This is probably due to [conf](https://www.npmjs.com/package/conf) which states:
> If you need this for Electron, check out [electron-store](https://www.npmjs.com/package/electron-store) instead.

nucleus-nodejs: 3.0.2
MacOS 10.14.1
Electron 6.1.4

**Comment by vincelwt** [comment]
Thanks for reporting. 
That's weird. Means that it failed to use the conf module, which should've still worked even with Electron. 
I made a change to the module that better handles the case where it's Electron (use the appropriate path just like electron-store) and not ignore if localStorage is not defined. 

Could you confirm the issue is resolved with 3.0.3 ?
